baseURL = ""
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Jeffrey Sica"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-M67G2EBPQV"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Jeffrey Sica"
author = "Jeffrey Sica"
description = """Software Engineer @ Red Hat<br />
Kubernetes Contributor<br />
CNCF Ambassador<br />
OSS Advocate<br />
DMs open. Honk.
"""
displayMode = "dark"
profilePicture = "/images/jeefy2.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/custom.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = [""]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/jeefy"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jeefy"

[[params.socialIcons]]
icon = "fab fa-twitch"
title = "Twitch"
url = "https://twitch.tv/jeef111x"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "YouTube"
url = "https://www.youtube.com/channel/UCF6KpKcKHIRx1WB2sP0DkhA"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/jeefy"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:me@jeefy.dev"

## Menu items

[menu]

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Presentations"
  weight = 300
  identifier = "presentations"
  url = "/presentation/"